### ISSUE TITLE
NO resolv.conf in kvm zone

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#298] opened 2017-11-17 10:23 UTC
Hi
I tried to make a kvm zone using ubuntu-certified-17.10 image from Smartos repos.
The kvm zone is created successfully but without the /etc/resolv.conf file.
Thank you
Paolo

**Comment by dn0** [comment] 2017-11-17 12:05
Hi Paolo,

Thank you for the information. These are not our official images, but we will try to reproduce the problem and then let you know if it can be fixed.

**Comment by dn0** [comment] 2017-11-17 13:38
Confirmed.
/etc/resolv.conf is correctly configured in the ubuntu-certified-16.04 image.
In ubuntu-certified-17.10 it stopped working probably due to some changes in cloud-init.

We will try to fix this in the next release.

Thank you for letting us know.

**Comment by dn0** [comment] 2017-11-21 21:20
Hi Paolo,

Originally, I was thinking that we can fix this by adding some metadata for cloud-init. Howerver, this is something that needs to be fixed in the image.

After playing around with the ubuntu-certified-17.10 image, I found that /etc/resolv.conf is a broken symlink to ../run/resolvconf/resolv.conf. There are at least two options to fix this:

* `rm -f /etc/resolv.conf; ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf` (the systemd-resolved service maintains `/run/systemd/resolve/resolv.conf` from the first boot)

OR

* `apt-get install resolvconf`

I've sent the information to the smartos-discuss mailing list.

**Closed by dn0** 2017-11-21 21:20 UTC
Labels: support

**Comment by dn0** [comment] 2018-02-15 15:36
This was fixed in ubuntu-certified 17.10 20171122
https://docs.joyent.com/public-cloud/instances/virtual-machines/images/linux/ubuntu-certified#1710-20171122
