### ISSUE TITLE
Create template using es tool fails with python 3.6 and windows

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#245] opened 2017-08-30 12:54 UTC
OS info: Python 3.6.2 for Windows

Failing call:
```
es set /template/MyTemp.1 -vm_define 'json::{"vcpus":1, "ram":4096}'
{
"method": "PUT",
"url": "...",
"status": 400,
"text": {
"status": "FAILURE",
"result": {
"vm_define": [
"Invalid value."
]
},
"task_id": "1d1u1-6f75849b-86c8-4c61-869b"
}
}
```
@ricco386 will provide more details on how to replicate it.

**Comment by ricco386** [comment] 2017-08-30 13:09
Seems to be working on `Python 3.6.2` on Linux, I can't reproduce it.

**Comment by secult** [comment] 2017-08-30 15:20
It may be related to some characters incorrectly represented, maybe "'"

**Comment by secult** [comment] 2017-09-07 09:52
In Windows 7 (and others too), single quotes are not threated as delimiters. 
To be able to pass any payload containing spaces etc, you have to use double quotes to enclose the payload. As a consequence, you have to escape double quotes in the payload. This is done easily in the cmd.exe, and rather more cumbersomely in the Powershell.

cmd: 
```
es set /template/MyTemp.1 -vm_define "json::{\"vcpus\":1, \"ram\":4096}"
```

powershell: 
```
es set /template/MyTemp.1 -vm_define "json::{`\`"vcpus`\`":1, `\`"ram`\`":4096}"
```

As this is not a bug, but Windows toolset UX problem, I'm closing this issue. 
PS: We will use Windows and Unix compatible representation in future examples in the documentation. See https://github.com/erigones/esdc-ce/pull/250.

**Closed** 2017-09-07 09:52 UTC
Labels: wontfix
