### ISSUE TITLE
esdc-dns deploy fails depending on the dns_resolvers in the config file

### ISSUE THREAD

**Issue by fishman** [erigones/esdc-ce#502] opened 2020-09-28 02:56 UTC
I used the following dns_resolvers in my config file:

```
dns_resolvers=213.133.98.98,213.133.99.99,213.133.100.100,2620:fe::fe,2620:fe::9
```
Installing with the config file leads to the esdc-dns deploy failing

```
-  "org.erigones:recursor_forwarders": ".=213.133.98.98;213.133.99.99,213.133.100.100,2620:fe::fe,262
0:fe::9",
- ]: [ID 702911 daemon.error] Redirecting queries for zone '.' with recursion to: 213.133.98.98:53, 213.133.99.99:53\r\n", "stream":"console" }
```

**Comment by YanChii** [comment] 2020-09-28 08:16
The problem is the IPv6 address. DC doesn't support it yet.

**Comment by YanChii** [comment] 2020-10-24 09:54
Closing for now. Providing IPv6 addresses without IPv6 support in DC doesn't make sense.

**Closed by YanChii** 2020-10-24 09:54 UTC
